# Generated by Django 3.2.5 on 2021-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carmanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('car_number', models.CharField(max_length=15)),
                ('mass', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
