# Generated by Django 3.2.5 on 2021-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_carmanagement_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExcel_Carmanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=15)),
                ('mass', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
